### PR TITLE
17 chavez

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Mario.

1.12 👍 
2.10 👍 
3.1 👍 

Algorithm 11 I din't find. Where is it?

Algorithm 12 I din't find. Where is it?

Algorithm 13 I din't find. Where is it?

Algorithm 14 I din't find. Where is it?

Algorithm 15 👍 (ThirdL_88Ex)

**Comment by ghost** [comment]
hello, those exercises are in my repository

**Comment by NemirovichMark** [comment]
Algo 14 I saw. Good 👍

**Comment by NemirovichMark** [comment]
Hello.

Algo 11 Wrong. It is not Binary Search. 

Algo 12. Wrong. Do not use sort there, please
see the example:
A [1, 3]
B[2, 4, 6]
C[1, 0, 0, 0, 0] from A
C[1, 2, 0, 0, 0] from B
C[1, 2, 3, 0, 0] from A
C[1, 2, 3, 4, 0] from B
C[1, 2, 3, 4, 6] from B

Algo 13. Wrong. Do not use sort there, please
see the example:
A [1, 3, 4]
B[2, 3, 4, 5, 6]
C[1, 0, 0, 0, 0, 0, 0, 0] from A
C[1, 2, 0, 0, 0, 0, 0, 0] from B
C[1, 2, 3, 0, 0, 0, 0, 0] from B
C[1, 2, 3, 3, 0, 0, 0, 0] from A
C[1, 2, 3, 3, 4, 0, 0, 0] from A
C[1, 2, 3, 3, 4, 4, 0, 0] from B
C[1, 2, 3, 3, 4, 4, 5, 0] from B
C[1, 2, 3, 3, 4, 4, 5, 6] from B

**Comment by NemirovichMark** [comment]
Well done, Mario!

You can come to class to defend 3rd lab. (**already did**)
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
