### PR TITLE
Lab_3

### PR DESCRIPTION
**Pull request by dshela**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dariya.

double.Parse & Convert.ToDouble is not acceptable anymore. Use try protection or TryParse instead.

1.11 You had to create a new (second) array with only positive elements inside (as you did in 2.5). You only showed the positive from first array.
for(int i =0; i<10; i++)
{
    str = Console.ReadLine();
    c[i] = double.Parse(str);
    if (c[i] > 0)
    {
        Console.Write(a[i]);
        Console.Write("");
    }
}

3.9 If elements are equal - it is not a ascending (or descending) sequence: [0 0 3 3] - 2 (you have 4)
if (S1[i] >= S1[i + 1])
    {
        cnt1 = 1;
    }
    if (S1[i] <= S1[i + 1])

+ make algorithms from 86-88 pages
image

**Comment by dshela** [comment]
i corrected the mistakes

**Comment by NemirovichMark** [comment]
Hello Dariya.

double.Parse & Convert.ToDouble is not acceptable anymore. Use try protection or TryParse instead. (12 times)

3.9 Nope. Only ascending (or descending) sequence have to be counted.
image

Algorithm 12. DRY - don't repeat yourself. It is good, that you understood 3 cases. But all equal lines merge to 1, please. Common things must not be copy-pasted

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
Well done!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
