### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by Temchikkk**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Artem.
Sorry for late answer.

You have to use try{} block only for input. Everything else have to be controlled with another tools (if-statements for division by zero, null-objects; array,Length for inder out of range)
image

Fix it in the all numbers. please.

2.9 DRY - don't repeat yourself. Use 1 loop only. And 1 if-statement before.
if (max1 > min1)
                {
                    for (int i = min1; i <= max1; i++, count++)
                    {
                        counter = counter + arr[i];
                    }
                    Console.WriteLine($"Ответ: {counter / count} ");
                }
                else
                {
                    for (int i = max1; i <= min1; i++, count++)
                    {
                        counter = counter + arr[i];
                    }
                    Console.WriteLine($"Ответ: {counter / count} ");

                }

3.1 In the task requires: use 1 loop for it:
for (int i = 0; i < chisl.Count; i++)
                {
                    if (chisl[i] > max)
                    {
                        max = chisl[i];
                    }

                }
                List<int> chisl2 = new List<int>();
                for (int i = 0; i < chisl.Count; i++)
                {
                    if (chisl[i] == max)
                    {
                        chisl2.Add(i);
                    }
                }
So unite to 1 loop, please.

3.9 Wrong. The sequence must not be interrupted.
input: [1 2 3 4 2 0 -2 -1 5 9 10]
output: 4
your: 8
Did you understand why do you use Max()? counterv > p always!
image

Algorithm 12. Read the task to the end, please. Also, input have to be for each array such as length required.
image

Algorithm 13. Wrong. Read the task more attentively. 
input: A [1 3 2] B [-2 6 2 4 0]
sort in descending and then merge to 1 array:
output: C [-2 0 2 2 3 4 6]

Algorithm 14. Do it by yourself, please: D.Reverse();

**Comment by Temchikkk** [comment]
Hello!
I don' t understand. What I should limit with try-catch?Input of string in
console?

сб, 12 нояб. 2022 г., 10:15 Mark ***@***.***>:

**Comment by Temchikkk** [comment]
And what means 2.9 DRY?

вс, 13 нояб. 2022 г., 01:40 Артём Васильев ***@***.***>:

**Comment by NemirovichMark** [comment]
Hello Artem.

try
{
s = Console.ReadLine();
int a = Int32.Parse(s);
}
catch{}
int square = a * a;

something like this.


DRY - means, in your program had to be minimum of copy-paste
image
image

It would be wonderful if you will think how to make your program simpler: minimize duplication, especially loops (for/foreach/while/do).

**Comment by Temchikkk** [comment]
hello!
Please, explain what is wrong with algorithm 12? Did I do everything as in
the task? (truncation of a larger array, and alternation of elements)

вс, 13 нояб. 2022 г., 20:17 Mark ***@***.***>:

**Comment by Temchikkk** [comment]
Also, what's wrong with algorithm 13?
1 ordered array is output to the console, consisting of the other two.


Also, what's the deadline of all Lab. Works?

вс, 13 нояб. 2022 г., 22:36 Артём Васильев ***@***.***>:

**Comment by NemirovichMark** [comment]
Algo 12
image

Algo 13. Read the task.
1. arrays A & B have to be sorted
2. from one of them we pick the min element while array C wouldn't filled
- For PC easier to sort 2 small arrays and then unite them than sort one large array. You made difficult work for your PC.
image
image
image


Also, what's the deadline of all Lab. Works?
- 30 of December

**Comment by Temchikkk** [comment]
Hello, what will my grade be if I send you the third laboratory and defend
myself the first time? (I ask because the errors were only due to the
optimization of some numbers and due to a misunderstanding of the essence
of one number due to the wording in the textbook)

**Comment by Temchikkk** [comment]
Is it right?
3.1
Snippet

int p9 = 0;int maxmax = -10000000;try
{
    Console.WriteLine("Введите кол-во элементов массива ");
    p9 = int.Parse(Console.ReadLine());
}catch { };
 if (p9 > 0)
{
    List<int> chisl = new List<int>(p9);
    int[]chisl2= new int[p9];
    for (int i = 0; i < p9; i++)
    {

        try
        {
            Console.WriteLine($"Введите элемент с индексом {i}:");
            chisl.Add(int.Parse(Console.ReadLine()));
        }
        catch { }



    }

    int y = 0;
    for (int i = 0; i < p9; i++)
    {

        if (chisl[i]>maxmax)
        {

            maxmax = chisl[i];

            y = 0;
            chisl2[y]=i;



        }
        else if (chisl[i]==maxmax)
        {
            y++;
            chisl2[y] = i;

        }


    }
    for(int i=0;i<=y; i++)
        Console.Write($"{chisl2[i]} ");


}else
{
    Console.WriteLine("Что-то пошло не так");
}


чт, 17 нояб. 2022 г. в 09:49, Артём Васильев ***@***.***>:

> Hello, what will my grade be if I send you the third laboratory and defend
> myself the first time? (I ask because the errors were only due to the
> optimization of some numbers and due to a misunderstanding of the essence
> of one number due to the wording in the textbook)
>

**Comment by NemirovichMark** [comment]
Yes, I can accept it.
Upload to patch-5, please

**Pull request closed without merging**
