### PR TITLE
Finish third lab

### PR DESCRIPTION
**Pull request by kepchek**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Nikita.

Convert is not acceptable without protection anymore (as Parse). Use TryParse for input, or place it in the try{}catch{} block.

2.10 Miss 1st element, if no positive elements.
image
image

2.11 Where is the output?
image

3.1 According to the task, you have to do it in one loop!
for (int i = 0; i < len; i++)
{
    if (array[i] > max)
    {
        max = array[i];
    }
}
for (int i = 0; i < len; i++)
{
    if (array[i] == max)
    {
        gigacounter++;
    }
}

3.5 Works right. Small mistake. 
image

Algo 13. Not working
image

**Comment by NemirovichMark** [comment]
Hello Nikita.

Convert is not acceptable without protection anymore (as Parse). Use TryParse for input, or place it in the try{}catch{} block.
image

2.10
image

2.11
image

Everything else done well 👍

**Comment by kepchek** [comment]
can you check my lab pls? And can i defend it tommorrow?

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
