### PR TITLE
3 labara 

### PR DESCRIPTION
**Pull request by khobaess**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Sophia.

As I said last time, Parse and Convert no more acceptable. Protect your work with TryParse or try/catch

1.11 Wrong answer. Read the task more attentive.
input: [1 0 2 -5 6 8 -9 4 0 -3]
expected: [1 0 2 6 8 4 0]
output: [1 0 2]

2.6 In the previous task could be so little value, that your program would not work correctly.
image
Use it after array declarated.
And... did you launch your work?
image

3.9 Discending should be counted too
image

image

Good luck.. But check your fix I would can probably only on Thursday.

**Comment by khobaess** [comment]
i'm fixed

**Comment by NemirovichMark** [comment]
Hello Sophia.

As I said last time, Parse and Convert no more acceptable. Protect your work with TryParse or try/catch

**Comment by NemirovichMark** [comment]
Index out of range.
aaa[i] = int.Parse(c[i]);
If I will input less than 10 element in a row (occsionally)

**Comment by NemirovichMark** [comment]
1.11 Better. Almost right. But the task was: create a New array with positive numbers only
for (int i = 0; i < 10; i++)
            //{
            //    if (aaa[i] > 0)
            //    {
            //        Console.Write($"{aaa[i]} ");
            //    }
            //}

**Comment by NemirovichMark** [comment]
2.6 Right!
3.9 Better. But still failed.
DRY - don't repeat yourself! Merge them to 1 loop.

**Comment by NemirovichMark** [comment]
Algo 12. Have to work with different array length. Read the last paragraph of the task.
And DRY

Good luck!

**Comment by khobaess** [comment]
#region algara 12
            int n;
            int.TryParse(Console.ReadLine(), out n);
            int[] A = new int[n];
            for (int i = 0; i < n; i++)
            {
                    do
                    {
                        Console.Write("введите число из а ");
                    }
                    while (!int.TryParse(Console.ReadLine(), out A[i]));
            }
                int[] B = new int[n];
            for (int i = 0; i < n; i++)
            {
                    do
                    {
                        Console.Write($"введите число из б ");
                    }
                    while (!int.TryParse(Console.ReadLine(), out B[i]));
            }
            int[] C = new int[n+n];
            int k = 0;
            for (int i = 0; i < n+n; i += 2)
            {
                C[i] = A[k];
                k++;
            }
                k = 0;
            for (int i = 1; i < n+n; i += 2)
            {
                C[i] = B[k];
                k++;
            }

            foreach (int x in C) Console.Write($"{x} ");

            #endregion


 #region L3Task9
            int[] a = new int[11] { 3, 6, 8, 3, 2, 1, -1, 1, 2, 1, 0 };
            int len = 0;
            int maxlen = 0;
            for (int i = 0; i < 10; ++i)
            {
                if (a[i + 1] >= a[i])
                {
                    len++;
                }
                else
                {
                    if (len > maxlen)
                    {
                        maxlen = len;
                        len = 1;
                    }
                }
            }
            if (len > maxlen)
                maxlen = len;
            for (int i = 0; i < 10; i++)
            {
                if (a[i] >= a[i + 1])
                {
                    len++;
                }
                else
                {
                    if (len > maxlen)
                    {
                        maxlen = len;
                        len = 1;
                    }
                }
            }

            if (len > maxlen) maxlen = len;
            Console.WriteLine(maxlen);

            #endregion


int[] aaa = new int[10];
            Console.WriteLine("Введите элементы массива через пробел");
            string s = Console.ReadLine();
            string[] c = s.Split(' ');
            int cc = 0;
            for (int i = 0; i < 10; i++)
            {
                aaa[i] = int.Parse(c[i]);
            }
            for (int i = 0; i < 10; i++)
            {
                if (aaa[i] > 0)
                {
                    Console.Write($"{aaa[i]} ");
                }
            }
            #endregion

**Comment by NemirovichMark** [comment]
Hello.

Algo 12. Please, do so that it works well with
int[] A = new int[n];
int[] B = new int[m]; 
where n >= m
and where n < m

And upload it as a file, not here.

**Comment by NemirovichMark** [comment]
Good!
You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
