### PR TITLE
Complete

### PR DESCRIPTION
**Pull request by Chybaka1338**
I do not know why, but there is also a pack of commits from another user

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Andrew.

Do not worry. It is history of this branch's changing (from my side).
 
#region Task2
static void Task1_10()  You solve not the task asked about. REad more attentively, please. P & Q do not belong to an array

#region Task2_1        Recomendation for the future:
static void Task2_5()  Instead of this, use temporaty variable, please (it is much easier and faster for PC)
                firstIndex = secondIndex + firstIndex;
                secondIndex = firstIndex - secondIndex;
                firstIndex = firstIndex - secondIndex;

#region Task3_1
static void Task3_1()  The task requires to seek MAX and INDEXES of the MAX in ONE LOOP!

#region Task3_4
static void Task3_9()  DRY - don't repeat yourself!!! Remove duplication, please.
image

 public static int BinnarySearch(int[] array, int element) DRY (small)
image

static void Task12() DRY - don't repeat yourself!!! Remove duplication, please.
image

**Comment by Chybaka1338** [comment]
in 3_1, I used one loop to search for the maximum element and its indexes

**Comment by Chybaka1338** [comment]
done

сб, 3 дек. 2022 г. в 15:51, Mark ***@***.***>:

**Comment by Chybaka1338** [comment]
I'm sorry, I forgot about 3_4

сб, 3 дек. 2022 г. в 17:17, Андрей Зоммер ***@***.***>:

**Comment by Chybaka1338** [comment]
finally done

**Comment by NemirovichMark** [comment]
Hello Andrew.

3.1 Nope. According to the task you have to search max element and counts indexes in one loop!
image
image

Everything else is correct 👍

**Comment by Chybaka1338** [comment]
done)

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
