### PR TITLE
labbb3

### PR DESCRIPTION
**Pull request by ibragimovaaa**
I will die if this doesn't work :(

### CODE REVIEW

**Comment by ibragimovaaa** [comment]
pls check

**Comment by NemirovichMark** [comment]
Hello Olga.

1.10 First solution is right.

2.11 Wrong answer when no positive elements at all:
image

I will check algorithms later

**Comment by NemirovichMark** [comment]
Hello again.

Algo 13 provides an error:
image

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
Hello Olga.

2.11 👍 

Algo 13 waits the fix

**Comment by NemirovichMark** [comment]
Hello.
Algorithm 13 IndexOutOfRange
image

**Comment by NemirovichMark** [comment]
Right!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
