### PR TITLE
lab3

### PR DESCRIPTION
**Pull request by dkarasevgthub**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitry.

Parse and Convert is not acceptable anymore. Defend them with try/catch or use TryParse

2.5 DRY - don't repeat yourself. Merge it, please.
if (minN < maxN)
            {
                for (i = minN + 1; i < maxN; i++)
                {
                    if (array[i] < 0)
                    {
                        outArr[j] = array[i];
                        j++;
                    }
                }
            }
            else
            {
                for (i = maxN + 1; i < minN; i++)
                {
                    if (arr[i] < 0)
                    {
                        outArr[j] = arr[i];
                        j++;
                    }
                }
            }

image

**Comment by dkarasevgthub** [comment]
Solution updated!

**Comment by NemirovichMark** [comment]
Algo 12. DRY - don't repeat yourself. You paste it 3 times:
 for (i = 0; i < n; i++)
                    {
                        outp.Add(arrA[i]);
                        outp.Add(arrB[i]);
                    }

Everything else done well.

**Comment by dkarasevgthub** [comment]
Solution finally fixed!

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
