### PR TITLE
Update 3rd_Lab.sln

### PR DESCRIPTION
**Pull request by ANNALOZOVSKAYA**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Anna.

It works wight. Good!
But I want to see more tasks:
image

**Comment by NemirovichMark** [comment]
Hello Anna. I wait solution till the evening.

**Comment by ANNALOZOVSKAYA** [comment]
I remember, sorry, I will send it today, I am weary sick right now 

суббота, 10 декабря 2022 г. в 12:45 +0300 от ***@***.***  ***@***.***>:

**Comment by NemirovichMark** [comment]
Oh. Hm. Okay than I can prolong deadline till Tuesday.
I wish you to get well.

**Comment by ANNALOZOVSKAYA** [comment]
Thank you very much



Отправлено из мобильной Почты Mail.ru


суббота, 10 декабря 2022 г. в 13:10 +0300 от ***@***.***  ***@***.***>:

**Comment by NemirovichMark** [comment]
Hello. Good job.

Mark in the class is confirmed (5).

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
