### PR TITLE
Lab 3, done

### PR DESCRIPTION
**Pull request by GorbachevVictor**
Good morning

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Protect the Convert!

**Comment by NemirovichMark** [comment]
Hello again Victor.

Algo 12: Last element wrong:
image

And Convert as I wrote above.

Everything else done right!

**Comment by NemirovichMark** [comment]
Hello Victor.
You doesn't fix it. I wouldn't accept 5th lab till you fix this one.

**Comment by NemirovichMark** [comment]
Well done!

**Comment by GorbachevVictor** [comment]
so, I can do and send lab5, right?


сб, 24 дек. 2022 г. в 16:09, Mark ***@***.***>:

**Pull request merged**
