### PR TITLE
Hello! This is my Lab_3

### PR DESCRIPTION
**Pull request by TimKonstantinov**
Can you help me please! Where can I found algorithm tasks?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Tim.

#region Task_1_11 Output array shouldn't have size more than positive elements' amount in the input array.

#region Task_2_5 Output array should have size the same as distance between max and min element instead of this:
double[] amountot = new double[nn - 2];

Also DRY - don't repeat yourself. Merge it, please to 1 cycle:
if (index_max > index_min)
            {
                for (int i = index_min + 1; i < index_max; i++)
                {
                    if (mas[i] < 0)
                    {
                        amountot[mm] = mas[i];
                        mm++;
                    }
                }
            }
            if (mm == 0) mm = 0;
            if (index_max < index_min)
            {
                for (int i = index_max + 1; i < index_min; i++)
                {
                    if (mas[i] < 0)
                    {
                        amountot[mm] = mas[i];
                        mm++;
                    }
                }
            }

2.9 DRY - don't repeat yourself. Merge it, please to 1 cycle:
else if (maxi > mini)
            {
                for (int i = (mini + 1); i < maxi; i++)
                {
                    sum += M[i];
                    n += 1;
                }
                Console.WriteLine($"Arithmetic mean = {sum / n}\n");
            }
            else
            {
                for (int i = (maxi + 1); i < mini; i++)
                {
                    sum += M[i];
                    n += 1;
                }
                Console.WriteLine($"Arithmetic mean = {sum / n}\n");

image

**Comment by TimKonstantinov** [comment]
Hello! I fixed my bugs and wrote algo tasks :)

**Comment by NemirovichMark** [comment]
Hello.

Algo 12 - make for different arrays by length.
Algo 14 - I want to see your reverse.

**Comment by TimKonstantinov** [comment]
I fixed algo tasks!

**Comment by NemirovichMark** [comment]
Hello Tim,

Interesting solutions. Cool!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
