### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by RomaNazarenko**
Please, check Lab3)

### CODE REVIEW

**Comment by RomaNazarenko** [comment]
?

**Comment by NemirovichMark** [comment]
Hello Roman.

Excuse me for late answer. 
1.11 Task requires another thing:
input [1 2 -5 -7 0 9 -8 3 3 -4]
output [1 2 9 3 3]
You claim from use input 10 positive elements instead.

2.6 In the class I will ask you how does Array.Resize works.

Algo 12. DRY - do not repeat youself.
for (int i = 0; i != ArrayC.Length; i++)
                    {
                        if (i % 2 == 0)
                        {
                            ArrayC[i] = ArrayA[j];
                            j++;
                        }
                        else
                        {
                            ArrayC[i] = ArrayB[k];
                            k++;
                        }
                    }

Algo 13. Do not comment (keep) ineffective code. Remove it!
//int j = 0;
                //for (int i = 0; i < ArrayA.Length; i++)
                //{
                //    ArrayC[j]=ArrayA[i];
                //    j++;
                //}
                //for (int i = 0; i < ArrayB.Length; i++)
                //{
                //    ArrayC[j] = ArrayB[i];
                //    j++;
                //}
                //Array.Sort(ArrayC);

**Comment by RomaNazarenko** [comment]
Well. I changed 1.11 and Algo12. Please, check it. Also I got a questions and you didn't reply me
1)  How can I open two projects simultaneously. By this I mean, I want to write Lab in main project. And  write a test code in parallel. In addition, I want to launch them not simultaneously)
2) The second question connected with error is in GMAIL with photo. Check message from 23.10.2022  21:46

**Comment by NemirovichMark** [comment]
Hello Roman. 
I have ssen your question on the mail now. Since it is my work mailbox, I wouldn't open it at weekends.
1. You have to add (not open!) the project
Снимок экрана (63)
You can switch the code with double click on the cs file and change the compiling project above.
image

2. https://learn.microsoft.com/ru-ru/visualstudio/msbuild/errors/msb3021?view=vs-2022
https://learn.microsoft.com/ru-Ru/visualstudio/msbuild/errors/msb3027?view=vs-2019

1.11 Instead null in that case you can write "continue"
//Array[i] > 0 ? list.Add(Array[i]) : null;        --------what should i write instead of null?  


You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
