### PR TITLE
Create My 3rd Lab

### PR DESCRIPTION
**Pull request by Anastasia-Kalashnikova**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Karina.

.Parse() - will kill your program. Protect it, please.

1.10 What about P>Q input? Any message or swop?

1.11 New array shouldn't have zeros!

2.5 Merge these 2 cycles to 1, please:
double max = original[0];
int imax = 0;
for (int i = 1; i < n; i++)
{
    if (original[i] > max)
    {
        max = original[i];
        imax = i;
    }
}
double min = original[0];
int imin = 0;
for (int i = 1; i < n; i++)
{
    if (original[i] < min)
    {
        min = original[i];
        imin = i;
    }
}

Merge it to 1 cycle, please:
if (imin < imax)
{
    for (int i = imin; i <= imax; i++)
    {
        if (original[i] < 0)
        {
            negative[p] = original[i];
            p += 1;
        }
    }
}

else
{
    for (int i = imax; i <= imin; i++)
    {
        if (original[i] < 0)
        {
            negative[p] = original[i];
            p += 1;
        }
    }
}
2.9 The same. Merge cycles


Actually, it is bad to resize an array every loop:
Array.Resize<double>(ref original, original.Length + 1);

Did you read the Theory.cs for this lab? There is a lot of another collections with simpler adding new elements.

3.9 You solved it only for increasing sequence. The task was: either increasing or decreasing.

3.12 Wrong solution. In the input array can be zeros and they should be printed in the output. (and final array shouldn't have additional zeros (size should be less if negative elements were in the input array))

3.13 Doesn't work:
image
Expected: 6 1 2 3

Algorithm 11
You had to solve it with binary search! Every loop range should divide by 2.

**Comment by Anastasia-Kalashnikova** [comment]
Hello, I’m not Karina 

I think you made a mistake when you sent the email. 

С уважением, Калашникова Анастасия 
Группа БИВТ-22-20

воскресенье, 9 октября 2022 г. в 00:06 +0300 от ***@***.***  ***@***.***>:

**Comment by NemirovichMark** [comment]
Sorry Anastasia. I mixed up your names. But the comments refer to your work.

Fix them, please.

**Comment by Anastasia-Kalashnikova** [comment]
Hello, I fixed all the mistakes you wrote about

**Comment by NemirovichMark** [comment]
Hello.

1.11 Should have the same length as positive numbers count
double[] result = new double[10];

Everything else done right!

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
