### PR TITLE
lab 3

### PR DESCRIPTION
**Pull request by zitaisan**
4 files -> one of these is algorithms. please, check and this file.

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Taisia.

1.10 The task requires another thing.

1.11 There have be size equal to count of positive numbers
double[] newma = new double[<=10];

2.10 If you know HOW does it work (inside), you can use it
//можно ли пользоваться встроенными методами или прописывать полностью функцию удаления?
                ma0 = ma0.Where((e, i00) => i00 != indexmin0).ToArray(); //удаляем только первое вхождение элемента
But LINQ requests is very hard topic, so be aware that I will ask you about it in the class

3.9 Read the task

3.12 You still have array size = input size

Algo 12. Read last paragraph
double[] ma1 = new double[l]; 
double[] ma2 = new double[k];

Algo 13 DRY - don't repeate youself. KISS - keep it simple, student
Remove nested loops, please
while ((ma[i] > b[j]))
                                {
                                    ma3[c] = ma[i];
                                    //Console.WriteLine($"ma3[c] -> {ma3[c]}, c -> {c}, ma[i] -> {ma[i]}, i -> {i}");
                                    i++;
                                    c++;

**Comment by zitaisan** [comment]
fixed errors on the lab

**Comment by NemirovichMark** [comment]
You log your changes very good! Well done!

About 1.10: it means that P & Q are not elements of the array. They can be any. So 2nd solution is right. But first is good for another task (as you described)
image


3.9 Almost right! Now you solve the task you asked about. But too much answer
image
And why it so hate negative numbers?
image
No need to count straight row:
image
image

3.12 I ment that output array have to be less than input and have length = #positive elements.

**Comment by NemirovichMark** [comment]
Good.

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
