### PR TITLE
Update 3rd_Lab.csproj

### PR DESCRIPTION
**Pull request by Toliyy**
Please check

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Anatoliy.

2.6 Square here:
 poxog_min = (b2[0] - sr_zn) * (b2[0] - sr_zn);
but simple compare here:
 if (poxog < poxog_min) 

3.1 I hope you know how does it works:
c_neww.RemoveAll(e => (e == 0));

3.12 If you understand how linq-request works.
you can change it:
for (int i = 0; i < len_c5; i++) - 1st loop
        {
            if (c5[i] < 0)
            {
                c5[i] = -1;
            }
        }
c5.RemoveAll(e => (e == -1)); - 2nd loop
to 
c5.RemoveAll(e => (e  < 0 )); - 1 loop only

image

**Comment by Toliyy** [comment]
I've finished everything

**Comment by NemirovichMark** [comment]
Hello Anatoliy.

2.6 Square here creates a mistake:
image

3.12 Do not remove zeros, please
image

Algo 12. Read the last sentence of the task.

**Comment by NemirovichMark** [comment]
image

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
