### PR TITLE
It's done

### PR DESCRIPTION
**Pull request by dmitryakimov2206283**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitry.

1.13
Very bad (use a cycle 7 Console.Write instead):
Console.WriteLine("Initial array:\t{0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}",
                numbers[0], numbers[1], numbers[2], numbers[3], numbers[4], numbers[5], numbers[6],
                numbers[7], numbers[8], numbers[9]);
            Console.WriteLine("Odd indexes: {0}, {1}, {2}, {3}, {4}",
                oddIndexes[0], oddIndexes[1], oddIndexes[2], oddIndexes[3], oddIndexes[4]);
            Console.WriteLine("Even indexes: {0}, {1}, {2}, {3}, {4}",
                evenIndexes[0], evenIndexes[1], evenIndexes[2], evenIndexes[3], evenIndexes[4]);

3.9 Narrow solution. You have to make it more universal.
   if (numbers[i] + 1 == numbers[i + 1])
else if (numbers[i] - 1 == numbers[i + 1])

Your program shoud count any (not only arifmetical) sequence:
1, 2, 5, 9, 4, 2, -5, -8, - 11, 3
max - 9, 4, 2, -5, -8, - 11 - length = 6

3.12 Use only 1 cycle for your solution (instead of 2 nested and 1 additional)
// Delete negative elements
            for (int i = 0; i < n - 1; i++)
            {
                if (numbers[i] < 0)
                {
                    int negativeNumber = numbers[i];
                    for (int j = i + 1; j < n; j++)
                    {
                        if (numbers[j] > 0)
                        {
                            numbers[i] = numbers[j];
                            numbers[j] = negativeNumber;
                            break;
                        }
                    }
                }
            }

            Console.Write("Result array:\t");
            for (int i = 0; i < n; i++)
            {
                if (numbers[i] < 0)
                    break;
                Console.Write($"{numbers[i]} ");
            }

3.13 The same. No need to sort your array!
// Delete equal elements
            for (int i = 0; i < n - 1; i++)
            {
                for (int j = i + 1; j < n; j++)
                {
                    if (numbers[j] == numbers[i])
                    {
                        int repeatingNumber = numbers[i];
                        int firstRepeatingIndex = j;

                        while (j < n)
                        {
                            if (numbers[j] != repeatingNumber)
                            {
                                numbers[firstRepeatingIndex] = numbers[j];
                                numbers[j] = repeatingNumber;
                            }

                            j++;
                        }

                        repeatingCount++;
                    }
                }
            }

            Console.Write("Result array:\t");
            for (int i = 0; i < n - repeatingCount; i++)
                Console.Write($"{numbers[i]} ");
            Console.WriteLine();


 #region Arrays union Why *2? Make it more universal.
n+m

**Comment by NemirovichMark** [comment]
Hello Dmitry.

3.9 DivisionByZero occured:
double previousRatio = (double)numbers[1] / numbers[0];
ratio = (double)nextNumber / currentNumber;

3.13 Write in the comment, please, indexes of elements that will be removed with your code:
Queue<int> uniqueNumbers = new Queue<int>(); 
            foreach (var number in numbers)
            {
                if (!uniqueNumbers.Contains(number))
                    uniqueNumbers.Enqueue(number);
            }
from the array: [0, 1, 2, 0, 3, 4, -5, 3, 1]

(it is good, that you use Queue, but I hope you read **how** does it works)

Fix 3.9, please and answer to 3.13

**Comment by dmitryakimov2206283** [comment]
Code'll remove this indexes: 3, 7, 8

**Comment by NemirovichMark** [comment]
Well done!

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
