### PR TITLE
Create 3rd_lab.cs

### PR DESCRIPTION
**Pull request by unsaid-azizov**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Said.
Sorry for delay.

I hope you learned how List methods work.

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Comment by unsaid-azizov** [comment]
Hello, unfortunately now I'm sick, I hope that I can protect the 3rd and 4th labs at the same time on another day, thanks!

**Comment by unsaid-azizov** [comment]
Mark Nemirovich, I participated in the hackathon and our team took second place, can I get extra points for this?

https://misis.ru/university/news/admission/2022-11/8222/

**Comment by NemirovichMark** [comment]
Cool!

Did you wrote on C# there? If you show me your code for that task, I will give you 5 points (as 10 lab).

**Comment by unsaid-azizov** [comment]
> Cool!
> 
> 
> 
> Did you wrote on C# there? If you show me your code for that task, I will give you 5 points (as 10 lab).

Sorry for the delay, unfortunately there is no C#, but we used pretty complex data structures and approaches to solve the task. I can give you a link to the repository or show code on the next lesson, anyway I used python, nodeJS for the backend and autocompletion system, in my opinion C# irrelevant for building ML systems in 3 days 😅. 

Thanks, Said

**Comment by unsaid-azizov** [comment]
> Cool!
> 
> 
> 
> Did you wrote on C# there? If you show me your code for that task, I will give you 5 points (as 10 lab).

Here link for the repo: https://github.com/proton-bit/TenderHack

**Pull request merged**
