### PR TITLE
3 lab 

### PR DESCRIPTION
**Pull request by KovalevNikolay710**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Nikolay.

1.11 Output array have to contain only positive elements (without zeros)
double[] negative = new double[<10];

2.9 DRY - don't repeat yourself. Merge it to 1 loop & 1 if-statement, plese
if (maxI > minI)
                {
                    for (int i = minI; i < maxI + 1; i++)
                    {
                        SUM += arr[i];
                        counter++;
                    }
                    Sr = SUM / counter;
                }
                if (minI > maxI)
                {
                    for (int i = maxI; i < minI + 1; i++)
                    {
                        SUM += arr[i];
                        counter++;
                    }
                    Sr = SUM / counter;
                }

2.10
image
Also you do not REMOVE element (last), you just leave it unprinted. The task was: remove.

3.1 IndexOutOfRange (see 2.9 error):
double max = Arr[0];
Also the task was: during one loop! So merge it:
for (int i = 0; i < n; i++)
                {
                    if (Arr[i] > max) max = Arr[i];
                }
                for (int i = 0; i < n; i++)
                {
                    if (Arr[i] == max)
                    {
                        Brr[counter] = i;
                        counter++;
                    }
                }

3.13 What, if there would one 0 in the input array? It will be lost :(
Also you didn't remove, only hide elements.
(creation of new array B and re-writing of the input array A = B is legally enough!)

image

**Comment by KovalevNikolay710** [comment]
Hello, I've redone

**Comment by NemirovichMark** [comment]
Hello.

Algo 12. Read the last sentence of the task and remake.

**Comment by NemirovichMark** [comment]
Good. Now it works well.

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
