### PR TITLE
hello, 3-rd lab is done

### PR DESCRIPTION
**Pull request by Alexey-Khviatskovich**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey

1.11 In the output array should not be zeros at all (you place them in the end).

1.13 Excellent solution!

2.6 Excellent solution!

2.10 Merge the cycle where you seek positive values and min positive value. And create a new array without only that element

2.11 Merge 2 cycles to 1

2.13 You no need to create an array with positive elements. Change the max element by it's index, using only 1 cycle. And 1 cycle for output in the end.

3.1 Wrong answer. Read the task more attentively.

3.5 Be aware that I will ask you to make sort by yourself on the defend.

3.8 The same about Sort and Revert.

3.9 Wrong answer. Read the task more attentively.

3.13 Do not use useless work. Do not sort an array in this task.

**Comment by NemirovichMark** [comment]
Hello Alexey.
2.10 You no need to create a new array with positive elements. Just find the minimum element, please. And provide the array without it
 double[] positive_array = new double[quality]; - remove it

//fixed but i didn't entirely understand - is it about 10 or 11?)

2.13 Bad solution. You no need to use separate method to find the max in all cycle. You can merge %2 check and >max and save the index.

3.9 Better to release it in one cycle for economy of processor time. Do it, please.

3.13 I understood that your solution is to find changes between the rows of numbers (like a stairs). But it consume processor time very much. You make 3 cycles (because Array.Sort use it too). Better to solve it with 2 cycles. But... it is difficult with simple array. Did you read the Theory.cs?

**Comment by Alexey-Khviatskovich** [comment]
в прошлом реквесте я не исправил 3_13

**Comment by NemirovichMark** [comment]
Hello Alexey. 

Yes, I got. Had no time at business trip,

Do you know how does it works? -> Distinct
In the class I will ask you to make it by yoerself.

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
