### PR TITLE
Create Solution.cs

### PR DESCRIPTION
**Pull request by unsaid-azizov**

### CODE REVIEW

**Comment by proton-bit** [comment]
Check this pull please 🥹

**Comment by NemirovichMark** [comment]
Hello Said.

2.6 Inserted before mid element. Expected: after.

2.11 The same. Did you checked the result?
image

3.1 Wrong. The task was: do it in one loop (you use 2)
if (value > max_elem)
                    {
                        max_elem = value;
                    }
                }

                for (int i = 0; i < n; i++)
                {
                    if (x[i] == max_elem)
                    {
                        indexes.Add(i);
                    }
                }

Sorry for delay.

**Comment by unsaid-azizov** [comment]
Thanks for the corrections, I'll be back soon 😁

**Comment by unsaid-azizov** [comment]
[](url)

**Pull request closed without merging**
