### PR TITLE
lab 3

### PR DESCRIPTION
**Pull request by OlegChavykin**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Protect Convert.ToInt32(Console.ReadLine()); with try/catch or TryParse

Later I check again

**Comment by NemirovichMark** [comment]
Hello Oleg.

1.11 Very interesting solution. But you write in the back order:
 array_positive2[count2 - 1] = array2[i];
        count2--;
To avoid it, start the loop from the end too:
for (int i = 10; i > 0; iii)

3.1 Read the task once more, please. You use 2 loops (try to find them here:)
double x = array.Max();
for (int i = 0; i < n; i++)
{
    if (array[i] == x)
    {
        s += Convert.ToString(i);
    }
}

3.9 Merge 2 loops to 1.
for (int i = 0; i < n - 1; i++)
{
    if (array[i] < array[i + 1])
    {
        temp++;
        max_pos = Math.Max(max_pos, temp);
    }
    else
    {
        temp = 1;
    }
}
temp = 1;
for (int i = 0; i < n - 1; i++)
{
    if (array[i] > array[i + 1])
    {
        temp++;
        max_neg = Math.Max(max_neg, temp);
    }
    else
    {
        temp = 1;
    }
}

3.12 A little bit wrong. You have to save zeros at their places.

Good luck with the fix.

**Comment by NemirovichMark** [comment]
Hello Oleg. 

Block "try" have to contain only user's unput (Parse/Convert). Everything else have to be after block "catch".

3.1 Still 2 loops used
double x = array.Max(); - here 1st one
        for (int i = 0; i < n; i++) - this is 2nd one
        {
            if (array[i] == x)
            {
                s += Convert.ToString(i);
            }
        }

3.9 Merge to 1 loop
image

3.12 Still wrong here:
if (array[i] < 0)
            {
                array[i] = 0;

**Comment by OlegChavykin** [comment]
I have corrected the mistakes. Check

**Comment by NemirovichMark** [comment]
Hello Oleg.

Interesting solution for 3.1 👍 

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Pull request merged**
