### PR TITLE
fixed 3-rd lab

### PR DESCRIPTION
**Pull request by Mihail-Shalyrin**
///

### CODE REVIEW

**Comment by Mihail-Shalyrin** [comment]
Look at the 2-cond file - its correct

**Comment by NemirovichMark** [comment]
Hello Mihail.

Parse and Convert is no longer acceptable. You can protect it with try/catch or change on TryParse.

1.10 Read the task more attentive, please
image

2.10 Good

3.9 Better. You have to count not only ascending sequence, but descending too.
image

3.12 Okay (but sort is not required)

3.13 All elements that have duplicates have to be removed (not only duplicates)
image

Algo 12 Read the last sequence of the task, please
image

Algo 13. Problem with last element
image

Good luck with fix!

**Comment by Mihail-Shalyrin** [comment]
i'am tried again

**Comment by NemirovichMark** [comment]
Hello Mihail.

3.13 Please, remove duplicated elements.
image
input: [1 2 3 2 3 0]
output: [1 0]

The output array have to be less than input (if there any doublicates). No need to fill it with zeros or anything else. You can check elemest on unic and add it to 2nd array.

Everything else works right.

**Comment by Mihail-Shalyrin** [comment]
and again

**Comment by NemirovichMark** [comment]
Hello Mihail.

It removes duplicates 👍 
Actually it is wrong that order is reverted. But it can be simply changed, so I won't ask you about it. But on the exam it would be critical.
image

You can come to class to defend 3rd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/4th_Lab

**Comment by NemirovichMark** [comment]
Also Parse & Convert not acceptable without protection (try+catch) anymore. Or use TryParse instead.

**Pull request merged**
