### PR TITLE
3-rd LAB

### PR DESCRIPTION
**Pull request by Mihail-Shalyrin**
1-rst attempt

### CODE REVIEW

**Comment by Mihail-Shalyrin** [comment]
Sorry, may be i'am don't understand something,but task 3.12 works corectly and in 2.10 i dont understand what is wrong.In 3.12 i am decided to replace elements < 0  with the maximum

**Comment by Mihail-Shalyrin** [comment]
in 3.13 i'am replaced element with "maximum + 1"

**Comment by NemirovichMark** [comment]
Hello Mihail.

2.10, 3.12 Task say: remove. Not skip, not change, not replase, not hide. Remove. So do it, please.
I understand that how you did, it looks like right. But it is wrong inside. Good programist do clear projects both: outside and inside.

3.13 Read once more, plese. Remove all elements that have a duplicates.
image

**Comment by NemirovichMark** [comment]
patch-2 was accepted

**Pull request closed without merging**
